### ISSUE TITLE
Logo design for ROS-TF-RobotIgniteAkaCourse

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/ROS-TF-RobotIgniteAkaCourse#1]
Hi @eduardorasgado, do you need a logo for this project too? It will be a pleasure for me to work again with you. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
@zuurw  Hi bro! I think you would like to work on a web game: Keybon.io here: https://github.com/eduardorasgado/keybon.io available at the moment on https://lalodigitaliza.me/keybon.io/ im still working on the development. It is quite simple, i know. I hope you accept it! cheers!

**Comment by zuurw** [comment]
Hi @eduardorasgado, do you want a logo for ROS-TF-RobotIgniteAkaCourse too? or do you want me to do only for the  Keybon.io?

Best Regards!

**Comment by eduardorasgado** [comment]
@zuurw Only for Keybon.io bro! I think ROS-TF does not deserves a logo haha. Check this project out too: https://github.com/eduardorasgado/podcastiny You're welcome to collaborate around this project. They both are finished projects. Take a look into them mate!
